Reorganization of config files; renaming variables about SuperSU

diff --git a/inc/ADB_functions b/inc/ADB_functions
--- a/inc/ADB_functions
+++ b/inc/ADB_functions
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+if ! ${EXEC}; then exit; fi
+
 function adb_delete_su_datas() {
 
     adb_su
@@ -32,16 +34,16 @@ function adb_delete_su_system() {
 
     adb_su
 
-    mssg=$(printf "${text_remove}\n" "${SU}")
+    mssg=$(printf "${text_remove}\n" "${SSU_SU}")
     display_mssg "n" "${mssg}" "" "2"
 
     adb shell "${adb_su}find /system/bin/.ext/ -type f -name '*su' -delete"
     adb shell "${adb_su}find '${SYS_BIN}' -type f -name 'sugote*' -delete"
-    adb shell "${adb_su}find '${SYS_BIN}' -type f -name '${SSUD}' -delete"
+    adb shell "${adb_su}find '${SYS_BIN}' -type f -name '${SSU_SSUD}' -delete"
     adb shell "${adb_su}find '${SYS_ETC}init.d' -type f -name 'daemonsu' -delete"
     adb shell "${adb_su}find '${SYS_ETC}' -type f -name '*installed_su_daemon' -delete"
     adb shell "${adb_su}find /system/bin/ -name 'su' -delete"
-    adb shell "${adb_su}find '${SYS_BIN}' -type f -name '${SU}' -delete"
+    adb shell "${adb_su}find '${SYS_BIN}' -type f -name '${SSU_SU}' -delete"
 
     mssg=$(printf "${text_datas_removed}\n" "system")
     display_mssg "n" "${mssg}"
@@ -52,7 +54,7 @@ function adb_delete_supersu() {
 
     adb_su
 
-    mssg=$(printf "${text_remove}\n" "${SuperSU}")
+    mssg=$(printf "${text_remove}\n" "${SSU_APK}")
     display_mssg "n" "${mssg}"
 
     adb shell "${adb_su}find '${SYS_APP}' -iname 'superuser*' -delete"
@@ -264,56 +266,64 @@ function adb_root_system() {
         sleep 1
         local ERROR=0
 
-        if [[ -f "${DIR_SSU}" ]]; then
+        if [[ -f "${SSU_DIR_APK}" ]]; then
+
             display_mssg "n" "${text_supersu_cp}${SYS_APP}"
-            adb push "${DIR_SSU}" "${SYS_APP}"
+            adb push "${SSU_DIR_APK}" "${SYS_APP}"
 
             display_mssg "n" "${text_supersu_chmod}${SYS_APP}"
-            adb shell 'if [[ -f "${SYS_APP}${SuperSU}" ]]; then chmod 0644 "${SYS_APP}${SuperSU}"; fi'
-            adb shell 'if [[ -f "${SYS_APP}${SuperSU}" ]]; then chown 0:0 "${SYS_APP}${SuperSU}"; fi'
+            adb shell 'if [[ -f "${SYS_APP}${SSU_APK}" ]]; then chmod 0644 "${SYS_APP}${SSU_APK}"; fi'
+            adb shell 'if [[ -f "${SYS_APP}${SSU_APK}" ]]; then chown 0:0 "${SYS_APP}${SSU_APK}"; fi'
             sleep 1
+
         else
-            mssg="$(printf "${text_error_file}" "${DIR_SSU}")"
+
+            mssg="$(printf "${text_error_file}" "${SSU_DIR_APK}")"
             display_error "${mssg}"
             ERROR=1
+
         fi
 
-        if [[ -f "${DIR_SU}" ]]; then
+        if [[ -f "${SSU_DIR_SU}" ]]; then
+
             display_mssg "n" "${text_su_cp}${SYS_BIN}"
-            adb push "${DIR_SU}" "${SYS_BIN}"
-            #adb shell cp "${SYS_BIN}${SU}" "${SYS_BIN}daemonsu"
-            #adb shell cp "${SYS_BIN}${SU}" "/system/bin/.ext/.${SU}"
+            adb push "${SSU_DIR_SU}" "${SYS_BIN}"
+            #adb shell cp "${SYS_BIN}${SSU_SU}" "${SYS_BIN}daemonsu"
+            #adb shell cp "${SYS_BIN}${SSU_SU}" "/system/bin/.ext/.${SSU_SU}"
             sleep 1
 
-            display_mssg "n" "chmod and chown ${SYS_BIN}${SU}"
+            display_mssg "n" "chmod and chown ${SYS_BIN}${SSU_SU}"
 
-            SDK=$(adb shell egrep ro.build.version.sdk /system/build.prop | dd bs=1 skip=21 count=2)
+            local SDK=$(adb shell egrep ro.build.version.sdk /system/build.prop | dd bs=1 skip=21 count=2)
             #SDK="$(adb shell grep ro.build.version.sdk /system/build.prop)"
             #echo "SDK: $SDK"
             #SDK="${SDK##*=}"
             echo "SDK: ${SDK}"
             if [[ "${SDK}" -gt 17 ]]; then
                 display_detected "SDK: ${SDK} > 17"
-                adb shell 'if [[ -f "${SYS_BIN}${SU}" ]]; then chmod 0755 "${SYS_BIN}${SU}"; fi'
-                #adb shell chmod 0755 "/system/bin/.ext/.${SU}"
+                adb shell 'if [[ -f "${SYS_BIN}${SSU_SU}" ]]; then chmod 0755 "${SYS_BIN}${SSU_SU}"; fi'
+                #adb shell chmod 0755 "/system/bin/.ext/.${SSU_SU}"
             else
                 display_detected "SDK: ${SDK} <= 17"
-                #adb shell 'if [[ -f "${SYS_BIN}${SU}" ]]; then chmod 06755 "${SYS_BIN}${SU}"; fi'
+                #adb shell 'if [[ -f "${SYS_BIN}${SSU_SU}" ]]; then chmod 06755 "${SYS_BIN}${SSU_SU}"; fi'
                 adb shell 'if [[ -f /system/xbin/su ]]; then chmod 06755 /system/xbin/su; fi'
-                #adb shell chmod 06755 "/system/bin/.ext/.${SU}"
+                #adb shell chmod 06755 "/system/bin/.ext/.${SSU_SU}"
             fi
             unset SDK
 
-            adb shell 'if [[ -f "${SYS_BIN}${SU}" ]]; then chown 0:0 "${SYS_BIN}${SU}"; fi'
-            adb shell "if [[ ! -h '/system/bin/${SU}' ]]; then ln -s ${SYS_BIN}${SU} /system/bin/${SU}; fi"
+            adb shell 'if [[ -f "${SYS_BIN}${SSU_SU}" ]]; then chown 0:0 "${SYS_BIN}${SSU_SU}"; fi'
+            adb shell "if [[ ! -h '/system/bin/${SSU_SU}' ]]; then ln -s ${SYS_BIN}${SSU_SU} /system/bin/${SSU_SU}; fi"
+
         else
-            mssg="$(printf "${text_error_file}" "${DIR_SU}")"
+
+            mssg="$(printf "${text_error_file}" "${SSU_DIR_SU}")"
             display_error "${mssg}"
             ERROR=1
+
         fi
 
         #adb shell chmod 0755 "${SYS_BIN}daemonsu"
-        #adb shell chown 0:0 "/system/bin/.ext/.${SU}"
+        #adb shell chown 0:0 "/system/bin/.ext/.${SSU_SU}"
 
         #display_mssg "n" "cp busybox into /tmp"
         #adb shell cp "${SYS_BIN}busybox" /tmp/busybox
@@ -330,10 +340,10 @@ function adb_root_system() {
 
         #display_mssg "i" "Verify ${SYS_ETC}init.d and create if not exists!"
             #adb shell "if [[ ! -d '${SYS_ETC}init.d' ]]; then mkdir '${SYS_ETC}init.d'; fi"
-            #adb push "${DIR_SSUD}" "${SYS_ETC}init.d"
+            #adb push "${SSU_DIR_SSUD}" "${SYS_ETC}init.d"
 
-            #adb shell chmod 0755 "${SYS_ETC}init.d/${SSUD}"
-            #adb shell chown 0:0 "${SYS_ETC}init.d/${SSUD}"
+            #adb shell chmod 0755 "${SYS_ETC}init.d/${SSU_SSUD}"
+            #adb shell chown 0:0 "${SYS_ETC}init.d/${SSU_SSUD}"
 
             #adb shell "if [[ ! -f '${SYS_ETC}.installed_su_daemon' ]]; then touch '${SYS_ETC}.installed_su_daemon'; fi"
             #adb shell "echo 1 > ${SYS_ETC}.installed_su_daemon"
@@ -341,7 +351,7 @@ function adb_root_system() {
             #adb shell chmod 0644 "${SYS_ETC}.installed_su_daemon"
             #adb shell chown 0:0 "${SYS_ETC}.installed_su_daemon"
 
-        #adb shell "${SYS_BIN}${SU} --install"
+        #adb shell "${SYS_BIN}${SSU_SU} --install"
 
         #adb shell chmod 04755 /system/xbin/busybox
         #adb shell chown 0:0 /system/xbin/busybox
@@ -365,6 +375,7 @@ function adb_root_system() {
         unset mssg ERROR
 
     fi
+
     unset search
 
 }
@@ -426,19 +437,24 @@ function adb_save_partitions() {
                 fi
 
             else
+
                 mssg="$(printf "${text_error_bckp}" "${ddof}")"
                 display_error "${mssg}"
 
                 write_file "log" "### $FUNCNAME: CANT saving Partition: ${DIR_SVG_DATED}/${MTD_NAME[${key}]}.img"
+
             fi
 
             if [[ "${ddname}" == "nvram" ]]; then
+
                 if [[ -z "$(adb_test "-f ${BCKP_PHONE}nvram.tgz")" ]]; then
+
                     adb pull "${BCKP_PHONE}nvram.tgz" "${DIR_SVG_DATED}"
                     adb shell rm -r "${BCKP_PHONE}nvram.tgz"
-                fi
-            fi
 
+                fi
+
+            fi
 
             sleep 1
 
@@ -494,12 +510,16 @@ function adb_write_img() {
         adb shell "${adb_su}dd if=${ddif} of=${ddof} bs=4096 count=${ddbs} skip=${ddskip}"
 
         if [[ $? -eq 0 ]]; then
+
             display_mssg "n" "dd if=${ddif} of=${ddof} bs=4096 count=${ddbs} skip=${ddskip}"
             write_file "log" "### $FUNCNAME: dd ${ddif} into ${ddof} [bs: 4096 | count: ${ddbs} | skip: ${ddskip}]"
+
         else
+
             mssg="$(printf "" "${ddif}")"
             display_error "${mssg}"
             display_mssg "n" "${text_sorry}"
+
         fi
 
     fi
@@ -513,9 +533,13 @@ function adb_stat_file() {
     local file="$1"
 
     if [[ "${vid}" != "${VID[0]}" ]]; then
+
         echo $( sed 's/\r$//' <<< $(adb shell stat -c "%s" "${file}") )
+
     else
+
         echo $( sed 's/\r$//' <<< $(adb shell ls -l "${file}" | awk '{print $5}') )
+
     fi
 
     unset file
@@ -526,9 +550,7 @@ function adb_su() {
 
     adb_su=""
 
-    if [[ "${vid}" != "${VID[0]}" ]]; then
-        adb_su="su -c "
-    fi
+    if [[ "${vid}" != "${VID[0]}" ]]; then adb_su="su -c "; fi
 
 }
 
diff --git a/inc/functions b/inc/functions
--- a/inc/functions
+++ b/inc/functions
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+if ! ${EXEC}; then exit; fi
+
 function MTKZenyTux() {
 
     echo -e "#################################"
@@ -19,6 +21,7 @@ function BACKUP() {
     if [[ "$1" == "" ]]; then
 
         in_array "${GUI}" "${GUIS[@]}";
+
         if [[ $? -eq 1 ]]; then
             display_feature_with_gui "${FUNCNAME}"
             display_menu
@@ -157,11 +160,14 @@ function FLASH() {
                 else
                     PART_CHOOSED[0]="${1#*=}"
                 fi
+
                 display_detected "PART_CHOOSED: ${PART_CHOOSED[@]}"
 
                 if [[ "$(count "${PART_CHOOSED[@]}")" -gt 0 ]]; then
+
                     for part in "${PART_CHOOSED[@]}"; do
                         local -i position=$(awk -v search=: '{print index($0,search)}' <<< "${part}")
+
                         if [[ "${position}" -gt 0 ]]; then
                             local name="${part:0:$position-1}"
                             local file="${part:$position}"
@@ -199,11 +205,17 @@ function FLASH() {
             if [[ "${files}" ]]; then files=($(explode " " "${files}")); fi
 
             if [[ -n "${files[@]}" ]]; then
+
                 for file in "${files[@]}"; do
+
                     if [[ -n "${file}" ]]; then
+
                         if [[ "${DIALOG}" -ne 0 ]]; then file="${MTD_NAME[${file}]}"; fi
+
                         choose_directory "f" "${text_choose_file}${file}";
+
                         if [[ -n "${FILE_CHOOSED}" ]]; then FILES_CHOOSED["${file}"]="${FILE_CHOOSED}"; fi
+
                     fi
                 done
             else
@@ -233,6 +245,7 @@ function REBOOT() {
 
         if [[ "${ZENITY}" -ne 0 ]]; then
             reboot=$( echos_menu_reboot | zenity_list "${text_reboot}" "${title_reboot}" "$(count ${MENU_REBOOT[@]})")
+
         elif  [[ "${DIALOG}" -ne 0 ]]; then
             echos_menu_reboot
 
@@ -478,12 +491,19 @@ function detect_device() {
         display_mssg "n" "${text_detect_dev}" "" "1";
     fi
 
-    for (( x=0; x < $(count "${VID[@]}") ; x++ )); do
-        lsusb=$(lsusb | egrep "${VID[$x]}")
+    for (( x=0; x < $(count "${PID[@]}") ; x++ )); do
+
+        if [[ $x -eq 0 ]]; then
+            vid="${VID[$x]}"
+        else
+            vid="${VID[1]}"
+        fi
+
+        lsusb=$(lsusb | egrep "${vid}")
 
         if [[ "${lsusb}" ]]; then
-            pid=${PID[$x]}
-            vid=${VID[$x]}
+            pid="${PID[$x]}"
+            #vid="${VID[$x]}"
             break;
         fi
 
@@ -503,32 +523,33 @@ function detect_device() {
 
     else
 
-        local mode=""
-
         display_detected "${text_VendorID}" "${vid}"
         display_detected "${text_ProductID}" "${pid}"
 
         if [[ "${vid}" == "${VID[0]}" ]]; then
-            mode="Mode: Recovery"
+            MODE="${MENU_REBOOT[0]}"
         else
-            mode="Mode: Session"
+            MODE="${MENU_REBOOT[1]}"
         fi
 
-        display_detected "${mode}"
+        local mssg="Mode: ${MODE}"
+        display_detected "${mssg}"
 
         if [[ "${DIALOG}" -ne 0 ]]; then
-            mssg="$(printf "%s" "\Z${bold}\Z${green}${text_VendorID}\n${text_ProductID}\n${mode}\Z${neutral}\Z${unbold}")"
+
+            mssg="$(printf "%s" "\Z${bold}\Z${green}${text_VendorID}\n${text_ProductID}\n${mssg}\Z${neutral}\Z${unbold}")"
             mssg="$(printf "${mssg}" "${vid}" "${pid}")";
             display_mssg "n" "${mssg}";
+
         elif [[ "${ZENITY}" -ne 0 ]]; then
-            mssg="$(printf "%s" "<span color=\"${green}\"><b>${text_VendorID}\n${text_ProductID}\n${mode}</b></span>")"
+
+            mssg="$(printf "%s" "<span color=\"${green}\"><b>${text_VendorID}\n${text_ProductID}\n${mssg}</b></span>")"
             mssg="$(printf "${mssg}" "${vid}" "${pid}")";
             display_mssg "i" "${mssg}" "${text_detect_dev}" "${title_detect_dev}";
+
         fi
 
-        if [[ "${mssg}" ]]; then
-            unset mssg
-        fi
+        if [[ "${mssg}" ]]; then unset mssg; fi
 
     fi
 
@@ -589,21 +610,25 @@ function explode() {
 
 function extract_archive_zip() {
 
-    if [[ -d "${DIR_SSU_UPD}" ]]; then
+    if [[ -d "${DIR_SSU}" ]]; then
 
         display_mssg "q" "${text_dir_ssu_upd}"
 
         if [[ "${ZENITY}" -ne 0 ]]; then
+
             REPLY=$?
+
         elif [[ "${DIALOG}" -ne 0 ]]; then
+
             REPLY="${read}"
+
         fi
 
         case "${REPLY}" in
             o|O|y|Y|0)
                 sleep 1 ;;
             n|N|1)
-                delete_dir "${DIR_SSU_UPD}"; sleep 3 ;;
+                delete_dir "${DIR_SSU}"; sleep 3 ;;
             *)
                 display_error "${text_choice_invalid}"
                 press_any_key
@@ -613,24 +638,24 @@ function extract_archive_zip() {
 
     fi
 
-    if [[ ! -d "${DIR_SSU_UPD}" ]]; then
+    if [[ ! -d "${DIR_SSU}" ]]; then
 
-        if [[ -f "${FILE_SSU_ZIP}" ]]; then
+        if [[ -f "${SSU_FILE_ZIP}" ]]; then
 
-            mssg=$(printf "\n${text_unzip}\n" "${FILE_SSU_ZIP}")
+            mssg=$(printf "\n${text_unzip}\n" "${SSU_FILE_ZIP}")
             display_mssg "n" "${mssg}"
             unzip -o "${DIR_UNZIP}" -d "${DIR_UNZIP}"
 
             if [[ $? -eq 0 ]]; then
-                mssg="$(printf "${text_unzip_ok}" "${FILE_SSU_ZIP}")"
+                mssg="$(printf "${text_unzip_ok}" "${SSU_FILE_ZIP}")"
                 display_mssg "n" "${mssg}"
 
-                write_file "log" "${NOW} ### $FUNCNAME: Unzip OK: ${DIR_TOOLS}UPDATE-SuperSU-${SSU_VERSION}"
+                write_file "log" "${NOW} ### $FUNCNAME: Unzip OK: ${SSU_DIR_UNZIP}"
             else
-                mssg="$(printf "${text_error_unzip}" "$?" "${FILE_SSU_ZIP}")"
+                mssg="$(printf "${text_error_unzip}" "$?" "${SSU_FILE_ZIP}")"
                 display_error "${mssg}"
 
-                write_file "log" "${NOW} ### $FUNCNAME: Unzip KO: ${DIR_TOOLS}UPDATE-SuperSU-${SSU_VERSION}"
+                write_file "log" "${NOW} ### $FUNCNAME: Unzip KO: ${SSU_DIR_UNZIP}"
 
                 press_any_key
                 EXIT
@@ -734,7 +759,6 @@ function file_stat() {
 function get_info_system() {
 
     # call: get_info_system partition_name
-
     adb_read_partitions
 
     extract_info_system "$1"
@@ -1125,10 +1149,10 @@ function unroot_to_system() {
 
 function verify_ssu_exists() {
 
-    if [[ ! -f "${FILE_SSU_ZIP}" ]]; then
+    if [[ ! -f "${SSU_FILE_ZIP}" ]]; then
 
-        mssg=$(printf "\n${text_app_inexistant}\n" "${SuperSU}")
-        mssg="${mssg}"$(printf "${text_app_dl}\n" "${SuperSU}" "${URL_SUPERSU}")
+        mssg=$(printf "\n${text_app_inexistant}\n" "${SSU_APK}")
+        mssg="${mssg}"$(printf "${text_app_dl}\n" "${SSU_APK}" "${SSU_URL}")
         mssg="${mssg}"$(printf "\n${text_ask_dl} ${text_yes_no}")
 
         display_mssg "q" "${mssg}" ""
@@ -1146,11 +1170,11 @@ function verify_ssu_exists() {
         while true; do
             case $REPLY in
                 y|Y|o|O|0)
-                    dl_file "${DL_SUPERSU}" "${FILE_SSU_ZIP}"
+                    dl_file "${SSU_DL}" "${SSU_FILE_ZIP}"
                     break
                 ;;
                 n|N|1)
-                    dl_yourself "${SuperSU}"
+                    dl_yourself "${SSU_APK}"
                 ;;
                 *)
                     display_error "${text_choice_invalid}"
@@ -1174,14 +1198,14 @@ function verify_ssu_exists() {
 
 function verify_archive() {
 
-    if [[ -f "${FILE_SSU_ZIP}" ]]; then
+    if [[ -f "${SSU_FILE_ZIP}" ]]; then
 
-        local key="$(array_search "${SSU_VERSION}" "${STATS_SSU_VERSION[@]}")"
-        local stat="$(stat -c "%s" "${FILE_SSU_ZIP}")"
+        local key="$(array_search "${SSU_VERSION}" "${SSU_STATS_VERSION[@]}")"
+        local stat="$(stat -c "%s" "${SSU_FILE_ZIP}")"
 
-        if [[ "${stat}" -ne "${STATS_SSU_SIZE[${key}]}" ]]; then
+        if [[ "${stat}" -ne "${SSU_STATS_SIZE[${key}]}" ]]; then
 
-            mssg="$(printf "${text_error_zip_ssu}" "${stat}" "${STATS_SSU_SIZE[${key}]}")"
+            mssg="$(printf "${text_error_zip_ssu}" "${stat}" "${SSU_STATS_SIZE[${key}]}")"
             display_error "${mssg}"
 
             dl_yourself
